import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,FileText,Wallet,ClipboardList,Settings,LogOut,Menu,X,Plus,Search,ChevronRight,Clock3,CheckCircle2,PlayCircle,PackageCheck,MoreHorizontal,Eye,Pencil,Copy,Trash2,SlidersHorizontal,UserRound,Building2,Phone,MapPin,Mail,ArrowLeft,Download,MessageCircle,AlertCircle} from 'lucide-react';
import './styles.css';

const quotes=[
 {id:'ORC-0024',client:'Mariana Souza',service:'Lavagem completa',date:'28/09/2026',value:2150,status:'Aguardando resposta',phone:'(21) 99999-1111',address:'Ipanema, Rio de Janeiro'},
 {id:'ORC-0023',client:'Carlos Almeida',service:'Manutenção preventiva',date:'27/09/2026',value:980,status:'Aprovado',phone:'(21) 98888-2222',address:'Tijuca, Rio de Janeiro'},
 {id:'ORC-0022',client:'Ana Paula',service:'Instalação de split',date:'25/09/2026',value:1450,status:'Em andamento',phone:'(21) 97777-3333',address:'Barra da Tijuca, Rio de Janeiro'},
 {id:'ORC-0021',client:'Eduardo Lima',service:'Higienização',date:'24/09/2026',value:620,status:'Concluído',phone:'(21) 96666-4444',address:'Botafogo, Rio de Janeiro'},
 {id:'ORC-0020',client:'Fernanda Costa',service:'Carga de gás',date:'22/09/2026',value:450,status:'Recusado',phone:'(21) 95555-5555',address:'Copacabana, Rio de Janeiro'}
];
const nav=[['home','Início',LayoutDashboard],['quotes','Orçamentos',FileText],['finance','Financeiro',Wallet],['tickets','Chamados',ClipboardList],['settings','Configurações',Settings]];
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function Badge({status}){let c=status.toLowerCase().replaceAll(' ','-');return <span className={'badge '+c}><i/> {status}</span>}
function App(){const [page,setPage]=useState('home');const [mobile,setMobile]=useState(false);const [selected,setSelected]=useState(null);const [search,setSearch]=useState('');
 const go=p=>{setPage(p);setSelected(null);setMobile(false)};
 return <div className="app"><aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="brandmark">F</div><div><strong>Frios&Clima</strong><small>Refrigeração</small></div><button className="close" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="profile"><div className="avatar">FC</div><div><strong>Frios&Clima</strong><small>Administrador</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button><LogOut size={18}/> Sair</button></div></aside>
 <main className="main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="header-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar orçamento, cliente..."/></div><div className="header-user"><div className="avatar small">FC</div><span>Frios&Clima</span></div></header>
 {selected?<QuoteDetail quote={selected} back={()=>setSelected(null)}/>:page==='home'?<Home go={go} setSelected={setSelected}/>:page==='quotes'?<Quotes search={search} setSelected={setSelected} go={go}/>:page==='finance'?<Finance setSelected={setSelected}/>:page==='tickets'?<Tickets setSelected={setSelected}/>:<SettingsPage/>}
 </main></div>}
function PageHead({title,sub,action}){return <div className="pagehead"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Home({go,setSelected}){return <div className="content"><PageHead title="Olá, Frios&Clima 👋" sub="Acompanhe seus orçamentos e serviços de hoje." action={<button className="primary" onClick={()=>go('quotes')}><Plus size={18}/> Novo orçamento</button>}/><div className="stats"><Stat icon={Clock3} label="Aguardando resposta" value="01" tone="orange"/><Stat icon={CheckCircle2} label="Aprovados" value="01" tone="green"/><Stat icon={PlayCircle} label="Em andamento" value="01" tone="blue"/><Stat icon={PackageCheck} label="Concluídos" value="01" tone="purple"/></div><section className="panel"><div className="panel-head"><div><h2>Orçamentos que precisam de atenção</h2><p>Acompanhe os clientes que ainda não responderam.</p></div><button className="link" onClick={()=>go('quotes')}>Ver todos <ChevronRight size={16}/></button></div><div className="attention"><div className="attention-icon"><AlertCircle size={20}/></div><div className="grow"><strong>ORC-0024 · Mariana Souza</strong><span>Lavagem completa · enviado em 28/09/2026</span></div><strong>{money(2150)}</strong><Badge status="Aguardando resposta"/><button className="iconbtn" onClick={()=>setSelected(quotes[0])}><Eye size={18}/></button></div></section><section className="panel"><div className="panel-head"><div><h2>Resumo financeiro</h2><p>Valores dos orçamentos aprovados.</p></div><button className="link" onClick={()=>go('finance')}>Ver financeiro <ChevronRight size={16}/></button></div><div className="finance-summary"><div><span>Setembro/2026</span><strong>{money(2430)}</strong></div><div><span>Orçamentos aprovados</span><strong>02</strong></div><div><span>Ticket médio</span><strong>{money(1215)}</strong></div></div></section></div>}
function Stat({icon:Icon,label,value,tone}){return <div className="stat"><div className={'stat-icon '+tone}><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Quotes({search,setSelected,go}){const filtered=quotes.filter(q=>(q.client+q.id+q.service+q.status).toLowerCase().includes(search.toLowerCase()));return <div className="content"><PageHead title="Orçamentos" sub="Crie, acompanhe e organize suas propostas." action={<button className="primary" onClick={()=>alert('Na V2 esta ação abrirá o formulário de criação de orçamento.') }><Plus size={18}/> Novo orçamento</button>}/><div className="toolbar"><div className="tabs"><button className="selected">Todos <b>05</b></button><button>Aguardando <b>01</b></button><button>Aprovados <b>01</b></button><button>Em andamento <b>01</b></button><button>Concluídos <b>01</b></button><button>Recusados <b>01</b></button></div><button className="filter"><SlidersHorizontal size={17}/> Filtros</button></div><div className="tablepanel"><table><thead><tr><th>Orçamento</th><th>Cliente</th><th>Serviço</th><th>Data</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(q=><tr key={q.id} onClick={()=>setSelected(q)}><td><strong>{q.id}</strong></td><td>{q.client}</td><td>{q.service}</td><td>{q.date}</td><td><strong>{money(q.value)}</strong></td><td><Badge status={q.status}/></td><td><button className="iconbtn"><MoreHorizontal size={19}/></button></td></tr>)}</tbody></table></div><div className="mobile-cards">{filtered.map(q=><div className="quote-card" key={q.id} onClick={()=>setSelected(q)}><div><strong>{q.id}</strong><Badge status={q.status}/></div><h3>{q.client}</h3><p>{q.service} · {q.date}</p><strong>{money(q.value)}</strong></div>)}</div></div>}
function QuoteDetail({quote,back}){return <div className="content"><button className="back" onClick={back}><ArrowLeft size={18}/> Voltar para orçamentos</button><PageHead title={quote.id} sub="Detalhes do orçamento" action={<div className="actions"><button className="secondary"><Pencil size={17}/> Editar</button><button className="secondary"><Download size={17}/> PDF</button><button className="primary"><MessageCircle size={17}/> WhatsApp</button></div>}/><div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Cliente</h2><p>Dados do solicitante</p></div><Badge status={quote.status}/></div><div className="info-grid"><Info icon={UserRound} label="Nome" value={quote.client}/><Info icon={Phone} label="Telefone" value={quote.phone}/><Info icon={MapPin} label="Endereço" value={quote.address}/><Info icon={Mail} label="E-mail" value="cliente@email.com"/></div></section><section className="panel"><div className="panel-head"><div><h2>Serviços</h2><p>Composição do orçamento</p></div></div><div className="service-line"><div><strong>Lavagem completa</strong><span>4 × Piso-Teto 60.000 BTU</span></div><strong>{money(1600)}</strong></div><div className="service-line"><div><strong>Lavagem completa</strong><span>1 × Split 12.000 BTU</span></div><strong>{money(250)}</strong></div><div className="service-line"><div><strong>Carga de gás</strong><span>1 × Split 12.000 BTU</span></div><strong>{money(300)}</strong></div><div className="total"><span>Total</span><strong>{money(quote.value)}</strong></div></section></div><section className="panel"><div className="panel-head"><div><h2>Observações e condições</h2></div></div><p className="note">Orçamento referente exclusivamente aos serviços descritos. Peças, reparos e materiais adicionais, caso necessários, serão cobrados à parte.</p></section></div>}
function Info({icon:Icon,label,value}){return <div className="info"><Icon size={17}/><div><small>{label}</small><span>{value}</span></div></div>}
function Finance({setSelected}){const approved=quotes.filter(q=>q.status==='Aprovado'||q.status==='Em andamento'||q.status==='Concluído');const total=approved.reduce((a,q)=>a+q.value,0);return <div className="content"><PageHead title="Financeiro" sub="Acompanhe os valores dos serviços aprovados."/><div className="finance-cards"><div className="bigmetric"><span>Total aprovado em setembro</span><strong>{money(total)}</strong><small>Valores vinculados a orçamentos aprovados.</small></div><div className="bigmetric"><span>Serviços aprovados</span><strong>{approved.length}</strong><small>Inclui em andamento e concluídos.</small></div></div><div className="tablepanel"><div className="table-title"><div><h2>Movimentações</h2><p>Clique em um item para consultar o orçamento.</p></div><select><option>Setembro 2026</option><option>Agosto 2026</option></select></div><table><thead><tr><th>Orçamento</th><th>Cliente</th><th>Data</th><th>Status</th><th>Valor</th></tr></thead><tbody>{approved.map(q=><tr key={q.id} onClick={()=>setSelected(q)}><td><strong>{q.id}</strong></td><td>{q.client}</td><td>{q.date}</td><td><Badge status={q.status}/></td><td><strong>{money(q.value)}</strong></td></tr>)}</tbody></table></div></div>}
function Tickets({setSelected}){const items=quotes.filter(q=>q.status!=='Recusado'&&q.status!=='Aguardando resposta');return <div className="content"><PageHead title="Chamados" sub="Serviços aprovados e em execução."/><div className="ticket-filters"><button className="selected">Todos <b>{items.length}</b></button><button>Aprovados</button><button>Em andamento</button><button>Concluídos</button></div><div className="ticket-list">{items.map(q=><div className="ticket" key={q.id} onClick={()=>setSelected(q)}><div className="ticket-num">CH-{q.id.split('-')[1]}</div><div className="grow"><strong>{q.client}</strong><span>{q.id} · {q.service}</span></div><strong>{money(q.value)}</strong><Badge status={q.status}/><ChevronRight size={18}/></div>)}</div></div>}
function SettingsPage(){return <div className="content"><PageHead title="Configurações" sub="Gerencie seus dados e as informações da empresa."/><div className="settings-grid"><section className="panel"><div className="panel-head"><div><h2>Perfil</h2><p>Dados de acesso e identificação.</p></div></div><label>Nome<input value="Frios&Clima" readOnly/></label><label>E-mail<input value="admin@friosclima.com.br" readOnly/></label><button className="secondary">Redefinir senha</button></section><section className="panel"><div className="panel-head"><div><h2>Dados da empresa</h2><p>Usados automaticamente nos próximos PDFs.</p></div></div><label>Nome da empresa<input value="Frios&Clima Refrigeração" readOnly/></label><label>CNPJ / CPF<input value="00.000.000/0001-00" readOnly/></label><label>Telefone / WhatsApp<input value="(21) 99999-9999" readOnly/></label><label>Endereço<input value="Rio de Janeiro - RJ" readOnly/></label><button className="secondary">Editar dados</button></section></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
